//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace Thesis_project_Repository.ServiceReference1 {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(Namespace="http://ISU/", ConfigurationName="ServiceReference1.ISUSMS")]
    public interface ISUSMS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [OperationContract(Action="http://ISU/ISUSMS/sendSMSISURequest", ReplyAction="http://ISU/ISUSMS/sendSMSISUResponse")]
        [XmlSerializerFormat(SupportFaults=true)]
        [return: MessageParameter(Name="return")]
        sendSMSISUResponse sendSMSISU(sendSMSISURequest request);
        
        [OperationContract(Action="http://ISU/ISUSMS/sendSMSISURequest", ReplyAction="http://ISU/ISUSMS/sendSMSISUResponse")]
        Task<sendSMSISUResponse> sendSMSISUAsync(sendSMSISURequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [OperationContract(Action="http://ISU/ISUSMS/sendSMSRequest", ReplyAction="http://ISU/ISUSMS/sendSMSResponse")]
        [XmlSerializerFormat(SupportFaults=true)]
        [return: MessageParameter(Name="return")]
        sendSMSResponse sendSMS(sendSMSRequest request);
        
        [OperationContract(Action="http://ISU/ISUSMS/sendSMSRequest", ReplyAction="http://ISU/ISUSMS/sendSMSResponse")]
        Task<sendSMSResponse> sendSMSAsync(sendSMSRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [OperationContract(Action="http://ISU/ISUSMS/getCarriersRequest", ReplyAction="http://ISU/ISUSMS/getCarriersResponse")]
        [XmlSerializerFormat(SupportFaults=true)]
        [return: MessageParameter(Name="return")]
        getCarriersResponse getCarriers(getCarriersRequest request);
        
        [OperationContract(Action="http://ISU/ISUSMS/getCarriersRequest", ReplyAction="http://ISU/ISUSMS/getCarriersResponse")]
        Task<getCarriersResponse> getCarriersAsync(getCarriersRequest request);
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(WrapperName="sendSMSISU", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class sendSMSISURequest {
        
        [MessageBodyMember(Namespace="http://ISU/", Order=0)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string username;
        
        [MessageBodyMember(Namespace="http://ISU/", Order=1)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string password;
        
        [MessageBodyMember(Namespace="http://ISU/", Order=2)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string provider;
        
        [MessageBodyMember(Namespace="http://ISU/", Order=3)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string number;
        
        [MessageBodyMember(Namespace="http://ISU/", Order=4)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string message;
        
        public sendSMSISURequest() {
        }
        
        public sendSMSISURequest(string username, string password, string provider, string number, string message) {
            this.username = username;
            this.password = password;
            this.provider = provider;
            this.number = number;
            this.message = message;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(WrapperName="sendSMSISUResponse", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class sendSMSISUResponse {
        
        [MessageBodyMember(Namespace="http://ISU/", Order=0)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendSMSISUResponse() {
        }
        
        public sendSMSISUResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(WrapperName="sendSMS", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class sendSMSRequest {
        
        [MessageBodyMember(Namespace="http://ISU/", Order=0)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string provider;
        
        [MessageBodyMember(Namespace="http://ISU/", Order=1)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string number;
        
        [MessageBodyMember(Namespace="http://ISU/", Order=2)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string message;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string provider, string number, string message) {
            this.provider = provider;
            this.number = number;
            this.message = message;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(WrapperName="sendSMSResponse", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class sendSMSResponse {
        
        [MessageBodyMember(Namespace="http://ISU/", Order=0)]
        [XmlElement(Form=XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(WrapperName="getCarriers", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class getCarriersRequest {
        
        public getCarriersRequest() {
        }
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    [MessageContract(WrapperName="getCarriersResponse", WrapperNamespace="http://ISU/", IsWrapped=true)]
    public partial class getCarriersResponse {
        
        [MessageBodyMember(Namespace="http://ISU/", Order=0)]
        [XmlElement("return", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getCarriersResponse() {
        }
        
        public getCarriersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface ISUSMSChannel : ISUSMS, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class SUSMSClient : ClientBase<ISUSMS>, ISUSMS {
        
        public SUSMSClient() {
        }
        
        public SUSMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SUSMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUSMSClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SUSMSClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        sendSMSISUResponse ISUSMS.sendSMSISU(sendSMSISURequest request) {
            return base.Channel.sendSMSISU(request);
        }
        
        public string sendSMSISU(string username, string password, string provider, string number, string message) {
            sendSMSISURequest inValue = new sendSMSISURequest();
            inValue.username = username;
            inValue.password = password;
            inValue.provider = provider;
            inValue.number = number;
            inValue.message = message;
            sendSMSISUResponse retVal = ((ISUSMS)(this)).sendSMSISU(inValue);
            return retVal.@return;
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<sendSMSISUResponse> ISUSMS.sendSMSISUAsync(sendSMSISURequest request) {
            return base.Channel.sendSMSISUAsync(request);
        }
        
        public Task<sendSMSISUResponse> sendSMSISUAsync(string username, string password, string provider, string number, string message) {
            sendSMSISURequest inValue = new sendSMSISURequest();
            inValue.username = username;
            inValue.password = password;
            inValue.provider = provider;
            inValue.number = number;
            inValue.message = message;
            return ((ISUSMS)(this)).sendSMSISUAsync(inValue);
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        sendSMSResponse ISUSMS.sendSMS(sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public string sendSMS(string provider, string number, string message) {
            sendSMSRequest inValue = new sendSMSRequest();
            inValue.provider = provider;
            inValue.number = number;
            inValue.message = message;
            sendSMSResponse retVal = ((ISUSMS)(this)).sendSMS(inValue);
            return retVal.@return;
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<sendSMSResponse> ISUSMS.sendSMSAsync(sendSMSRequest request) {
            return base.Channel.sendSMSAsync(request);
        }
        
        public Task<sendSMSResponse> sendSMSAsync(string provider, string number, string message) {
            sendSMSRequest inValue = new sendSMSRequest();
            inValue.provider = provider;
            inValue.number = number;
            inValue.message = message;
            return ((ISUSMS)(this)).sendSMSAsync(inValue);
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        getCarriersResponse ISUSMS.getCarriers(getCarriersRequest request) {
            return base.Channel.getCarriers(request);
        }
        
        public string[] getCarriers() {
            getCarriersRequest inValue = new getCarriersRequest();
            getCarriersResponse retVal = ((ISUSMS)(this)).getCarriers(inValue);
            return retVal.@return;
        }
        
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        Task<getCarriersResponse> ISUSMS.getCarriersAsync(getCarriersRequest request) {
            return base.Channel.getCarriersAsync(request);
        }
        
        public Task<getCarriersResponse> getCarriersAsync() {
            getCarriersRequest inValue = new getCarriersRequest();
            return ((ISUSMS)(this)).getCarriersAsync(inValue);
        }
    }
}
